### ISSUE TITLE
Team login doesn't  work properly till restart

### ISSUE THREAD

**Issue by captn3m0** [plaidchat/plaidchat#96] opened 2015-06-27 08:09 UTC
If I login to a new team, it assigns the top-most logged in team as the new team. Clicking on the top-most "old team" icon takes me to the new team. Explanation:

- Team 1
- Team 2

I click login to a new team on Team 1 page. After login what I see is still the same:

- Team 1
- Team 2

However, clicking on Team 1 actually takes me to Team 3, which I just logged in to. There is no way to access Team 1 again till I restart plaidchat. I am using plaidchat 2.0.1 with node 0.10.22

**Comment by captn3m0** [comment] 2015-06-27 08:16
Here's a screenshot. I'm clearly logged in to 4 teams, but only 2 are shown on the left. Also note that the chosen team is Team 1 (Razorpay), but the window shows Team 4

![2015-06-27-134528_1920x1080_scrot](https://cloud.githubusercontent.com/assets/584253/8391132/d391d788-1cd2-11e5-8d5c-77c12de221d4.png)

**Comment by twolfson** [comment] 2015-06-27 08:31
Please upgrade to the latest version. This was patched in 2.2.0 when we moved to React which seamlessly picks up new teams.

**Comment by captn3m0** [comment] 2015-06-28 20:41
Still facing the same issue in 2.4.0:

![screenshot_2015-06-29_02-09-59](https://cloud.githubusercontent.com/assets/584253/8398240/1427d658-1e04-11e5-996e-3bce65868604.png)

**Comment by twolfson** [comment] 2015-06-28 22:46
Ooooh, I see what's happening. It looks like "larachat" claimed "Razorpay's" tab without generating a new one (or restoring the old one). I believe the problem is we are accidentally aliasing "larachat" as "Razorpay". I can think of potential 2 approaches to fix this:

- Inside of each Slack window, add `body` level event listener for any `a` clicks
    - If the link is to `login.slack.com`, then prevent the link from running and instead open/activate a new placeholder login tab
    - Potential problems: Doesn't prevent `window.location` JS from running
- Generate new tab for "larachat" upon completed login and restore "Razorpay" tab (i.e. fix the current overzealoous aliasing)
    - Potential problems: While this works, it's janky to reload a tab that was already loaded. This is also redundant to the upcoming "Add new team" sidebar button

**Comment by twolfson** [comment] 2015-06-28 22:56
In order to set expectations, there is prob a good amount of work to be done here:

- Set up integration tests (this is too complex to test manually)
    - https://github.com/nwjs/nw.js/wiki/Chromedriver
    - https://github.com/pose/webdriver-manager
    - https://github.com/twolfson/google-music.js/blob/3.0.0/test/utils/browser.js
- Add support for "new team" button in sidebar
    - Should deselect all active tabs (or generate a `?` team icon) and show a login window
- Integrate `a` click override with clicking "new team" button in sidebar

I am going to give an ETA of 2 weeks to give us plenty of buffer time.

**Comment by twolfson** [comment] 2015-07-13 03:51
I was able to add test support but fell short on delivering "new team" support and the fix for this bug. It should take another week before it's all said and done. Sorry for the inconvenience.

**Comment by twolfson** [comment] 2015-07-18 07:06
#109 is open and should patch this issue. Additionally, it includes tests to prevent this error from occurring again =)

**Closed** 2015-07-18 22:48 UTC
Labels: bug

**Comment by twolfson** [comment] 2015-07-18 22:51
This has been patched/released in`2.8.0`
