### ISSUE TITLE
Icon looks blurry

### ISSUE THREAD

**Issue by aroman** [plaidchat/plaidchat#117] opened 2015-07-24 02:53 UTC
Hey,

Thanks for this great project :-)

It seems like the dock icon is using the 32x32 rather than the 256x256 icon -- any idea what's up with that?

![screenshot from 2015-07-23 22 50 46](https://cloud.githubusercontent.com/assets/531504/8866721/ac139c6c-318d-11e5-906e-87333ccdd071.png)

**Comment by twolfson** [comment] 2015-07-24 03:08
I am using Cinnamon which has a menu bar over a dock which is probably why we haven't run into this yet. What dock/OS are you using?

**Comment by aroman** [comment] 2015-07-24 03:18
elementary OS with Plank (the dock the OS uses)

**Comment by twolfson** [comment] 2015-07-25 07:17
I have successfully reproduced the issue via a VM. Trying to find the source.

**Comment by twolfson** [comment] 2015-07-25 08:24
After some sleuthing, it looks like this is a problem inside of Elementary OS. Any non-`.desktop` application seems to receive a blurry icon.

https://www.reddit.com/r/elementaryos/comments/2kx77b/how_to_fix_blurry_icons_on_plank/

To remedy the issue, please add the following file to your system (`.local/share/applications/plaidchat.desktop`):

```
[Desktop Entry]
Name=Plaidchat
Exec=plaidchat
Type=Application
Icon=/home/todd/github/plaidchat/app/images/app-256.png
# Replace this with the path to your plaidchat
# This can be found via:
# ls "$(dirname "$(which plaidchat)")/$(dirname "$(readlink "$(which plaidchat)")")/app/images/app-256.png"
#   which is most likely
#   /usr/lib/node_modules/plaidchat/app/images/app-256.png
```

I am going to close this issue as a duplicate of #102 since that is a more generic issue about installing `.desktop` files.

**Closed by twolfson** 2015-07-25 08:24 UTC

**Comment by twolfson** [comment] 2015-07-25 08:28
I should mention that once this file is created. You will have to log out/log in and select "Plaidchat" via the "Applications" launcher to get the new shiny/non-blurry icon.

**Comment by aroman** [comment] 2015-07-27 01:09
really appreciate your taking the time to look into this! I was aware of the issue with Chrome but I didn't realize it was a problem for all apps without .desktop files. I'll file appropriate upstream bugs :-)
